env: order-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order #\u670D\u52A1\u540D\u79F0
  datasource:
     url: jdbc:mysql://localhost:3306/day0309?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
     username: root
     password: root
     driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.0.108
    username: guest
    password: guest
    port: 5672
server:
  port: 9090
product:
  ribbon:
    NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule  
